### ISSUE TITLE
semi-major change botMan

### ISSUE THREAD

**Issue by daffavcd** [chicken-porridge/ticketing-api-bot#34]
field gunakan foreign key hilang, gaada ambil pt dari table lain,tambah input instance name ambe, adress
![image](https://user-images.githubusercontent.com/59133143/156367529-b4ecb1be-092d-472c-8334-fdb4c714bde3.png)

**Comment by refido** [comment]
on it

**Comment by daffavcd** [comment]
status langsung auto "Open" saat ada issue baru kyae. coba cekken

**Comment by refido** [comment]
Uda auto Open, Apa perlu ganti?
Masi pake db lama, perlu test di db baru?
